### ISSUE TITLE
Could not initialize class de.tum.in.test.api.io.IOTester

### ISSUE THREAD

**Issue by Wallenstein61** [ls1intum/artemis-java-test-sandbox#42]
**Describe the bug**
I get an error message: BAD PATH ACCESS: C:\Users\Michael Breu\git\uibk3sandbox-solution\bin\de\tum\in\test\api\io\StaticLine.class (BL:false, WL:false)

**To Reproduce**

I have set up a test für the Standard SortingPatternExample and adapted it to use it with the test sandbox

```java
    @Test
    @Public
    @StrictTimeout(value = 1000, unit = TimeUnit.MILLISECONDS)
    @WhitelistPaths({@WhitelistPath("target"),@WhitelistPath("pom.xml")})
    @WhitelistPackages({    @WhitelistPackage("java.lang.reflect"), @WhitelistPackage("at.ac.uibk.qe.artemis.testsandbox")})
    public void testUseMergeSortForBigList() throws IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, InstantiationException, ClassNotFoundException {
        List<Date> bigList = new ArrayList<Date>();
        for (int i = 0; i < 11; i++) {
            bigList.add(new Date());
        }
        Object chosenSortStrategy = configurePolicyAndContext(bigList);
        if (!(chosenSortStrategy instanceof MergeSort)) {
            fail("The sort algorithm of Context was not MergeSort for a list with more than 10 dates.");
        }
    }
```
It seems to trigger this problem, because inside Policy.java there is a System.out.println(...)

**Expected behavior**
I should not need to whitelist the sandbox itself.

**Desktop (please complete the following information):**
- locally stated in eclipse.
- Sandbox Version v1.0.1

**Comment by MaisiKoleni** [comment]
I tested a bit and I guess you have included AJTS locally from Eclipse in some way like 
```
- Eclipse Project
   - src
      - at/ac/uibk/qe/artemis/testsandbox (your code)
      - de/tum/in/test/api/... (the AJTS source code)
   - bin (the same structure as src but with the class files, generated by eclipse)
   - target (used by maven, most likely)
```

The problem is that the class loader tries to load class files from the bin folder, which is not permitted. In the code you showed, only `target` is whitelisted.

This is in two ways unexpected:
- `target` is not used, but `bin`. Eclipse should use `target` as well, which is normally does, but it could be the problem that the project has not been updated and is still using an old/wrong `.classpath`. Project -> Maven ->Update Project might help.
- AJTS is not included using Maven if I analyzed that correctly. While it should work by just including the sources as well, using the .jar via Maven might work better.

Please let me know if that solved the issue. You can contact me directly if you want to get an introduction (the documentation is not complete, as it has only been used internally until now. I plan to improve and extend the documentation a lot in the next weeks and offer it over a website, like JUnit), any other help or advice, or if you require other/new features.

**Comment by Wallenstein61** [comment]
Thank you for your extensive answer and your great tool.

Indeed this might be the problem. I tested it inside eclipse (for easier debugging).

Michael
